export const blogs = [
  {
    id: 1,
    title: "Blog 1",
    image:
      "https://images01.nicepage.com/c461c07a441a5d220e8feb1a/a17abde8d83650a582a28432/users-with-speech-bubbles-vector_53876-82250.jpg",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla quo iusto perferendis aperiam error tenetur vel aliquid voluptate cupiditate nesciunt ipsa, quia laboriosam perspiciatis atque corporis, illo, dolorum fugit asperiores alias dignissimos illum voluptates quasi nobis. Sit ipsam libero, quod vitae amet similique possimus fugit corporis molestias vero, repellendus laudantium sed fugiat dolorum iusto rem beatae! Ut libero sit quaerat eius, laborum dicta pariatur animi ipsa odio officiis et! Culpa odio excepturi accusamus corporis nihil, labore dolorum illo cupiditate rerum odit natus voluptatibus adipisci ipsa modi cumque amet repellat placeat corrupti ullam molestiae distinctio! Ab odio quibusdam quos iure, explicabo facilis recusandae eveniet ea, quod adipisci similique minus tempora nihil, natus nobis est excepturi quaerat doloremque cumque hic dolorum? Sint odit repellat labore accusamus corrupti vero et, necessitatibus optio quas, maiores nesciunt odio veniam. Repellat, ducimus! Possimus, soluta illo, modi repellendus, reprehenderit dolores totam error architecto ut asperiores cum rem sunt blanditiis a quas vitae quo atque libero aliquam consequuntur inventore vero ullam ipsum velit! Molestiae, explicabo. Odio doloribus corporis, in totam ex architecto. Ab tenetur nisi sapiente officia aspernatur blanditiis. Ab, rerum quos ex modi corrupti blanditiis quo dicta numquam quia ipsam suscipit praesentium sit provident animi aspernatur ratione magni nesciunt maxime atque culpa nemo voluptas amet repudiandae. Aperiam, doloremque nesciunt omnis alias, asperiores, architecto aut iure modi aspernatur sed saepe dolor velit atque dicta deserunt impedit error dolore! Quod repudiandae aut consequuntur facere explicabo labore corporis reprehenderit ipsa! Dolores impedit similique exercitationem, esse nobis, cumque voluptatum illum quasi ea nostrum sit voluptatibus totam amet provident accusantium et tenetur quod dignissimos architecto. Atque assumenda, eligendi fugiat hic suscipit amet natus. Aut repudiandae animi dignissimos ea aliquid sed rerum enim doloribus qui culpa nobis ratione minus asperiores eum delectus, quas repellendus cum autem veniam iure at! Dicta, ab. Eligendi, qui!",
    category: "category 1",
  },
  {
    id: 2,
    title: "Blog 2",
    image:
      "https://images01.nicepage.com/c461c07a441a5d220e8feb1a/3b242447f922540fbe750cab/fdf.jpg",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla quo iusto perferendis aperiam error tenetur vel aliquid voluptate cupiditate nesciunt ipsa, quia laboriosam perspiciatis atque corporis, illo, dolorum fugit asperiores alias dignissimos illum voluptates quasi nobis. Sit ipsam libero, quod vitae amet similique possimus fugit corporis molestias vero, repellendus laudantium sed fugiat dolorum iusto rem beatae! Ut libero sit quaerat eius, laborum dicta pariatur animi ipsa odio officiis et! Culpa odio excepturi accusamus corporis nihil, labore dolorum illo cupiditate rerum odit natus voluptatibus adipisci ipsa modi cumque amet repellat placeat corrupti ullam molestiae distinctio! Ab odio quibusdam quos iure, explicabo facilis recusandae eveniet ea, quod adipisci similique minus tempora nihil, natus nobis est excepturi quaerat doloremque cumque hic dolorum? Sint odit repellat labore accusamus corrupti vero et, necessitatibus optio quas, maiores nesciunt odio veniam. Repellat, ducimus! Possimus, soluta illo, modi repellendus, reprehenderit dolores totam error architecto ut asperiores cum rem sunt blanditiis a quas vitae quo atque libero aliquam consequuntur inventore vero ullam ipsum velit! Molestiae, explicabo. Odio doloribus corporis, in totam ex architecto. Ab tenetur nisi sapiente officia aspernatur blanditiis. Ab, rerum quos ex modi corrupti blanditiis quo dicta numquam quia ipsam suscipit praesentium sit provident animi aspernatur ratione magni nesciunt maxime atque culpa nemo voluptas amet repudiandae. Aperiam, doloremque nesciunt omnis alias, asperiores, architecto aut iure modi aspernatur sed saepe dolor velit atque dicta deserunt impedit error dolore! Quod repudiandae aut consequuntur facere explicabo labore corporis reprehenderit ipsa! Dolores impedit similique exercitationem, esse nobis, cumque voluptatum illum quasi ea nostrum sit voluptatibus totam amet provident accusantium et tenetur quod dignissimos architecto. Atque assumenda, eligendi fugiat hic suscipit amet natus. Aut repudiandae animi dignissimos ea aliquid sed rerum enim doloribus qui culpa nobis ratione minus asperiores eum delectus, quas repellendus cum autem veniam iure at! Dicta, ab. Eligendi, qui!",
    category: "category 2",
  },
  {
    id: 3,
    title: "Blog 3",
    image:
      "https://images01.nicepage.com/c461c07a441a5d220e8feb1a/8cc47b39e719570b996d9879/dsds.jpg",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla quo iusto perferendis aperiam error tenetur vel aliquid voluptate cupiditate nesciunt ipsa, quia laboriosam perspiciatis atque corporis, illo, dolorum fugit asperiores alias dignissimos illum voluptates quasi nobis. Sit ipsam libero, quod vitae amet similique possimus fugit corporis molestias vero, repellendus laudantium sed fugiat dolorum iusto rem beatae! Ut libero sit quaerat eius, laborum dicta pariatur animi ipsa odio officiis et! Culpa odio excepturi accusamus corporis nihil, labore dolorum illo cupiditate rerum odit natus voluptatibus adipisci ipsa modi cumque amet repellat placeat corrupti ullam molestiae distinctio! Ab odio quibusdam quos iure, explicabo facilis recusandae eveniet ea, quod adipisci similique minus tempora nihil, natus nobis est excepturi quaerat doloremque cumque hic dolorum? Sint odit repellat labore accusamus corrupti vero et, necessitatibus optio quas, maiores nesciunt odio veniam. Repellat, ducimus! Possimus, soluta illo, modi repellendus, reprehenderit dolores totam error architecto ut asperiores cum rem sunt blanditiis a quas vitae quo atque libero aliquam consequuntur inventore vero ullam ipsum velit! Molestiae, explicabo. Odio doloribus corporis, in totam ex architecto. Ab tenetur nisi sapiente officia aspernatur blanditiis. Ab, rerum quos ex modi corrupti blanditiis quo dicta numquam quia ipsam suscipit praesentium sit provident animi aspernatur ratione magni nesciunt maxime atque culpa nemo voluptas amet repudiandae. Aperiam, doloremque nesciunt omnis alias, asperiores, architecto aut iure modi aspernatur sed saepe dolor velit atque dicta deserunt impedit error dolore! Quod repudiandae aut consequuntur facere explicabo labore corporis reprehenderit ipsa! Dolores impedit similique exercitationem, esse nobis, cumque voluptatum illum quasi ea nostrum sit voluptatibus totam amet provident accusantium et tenetur quod dignissimos architecto. Atque assumenda, eligendi fugiat hic suscipit amet natus. Aut repudiandae animi dignissimos ea aliquid sed rerum enim doloribus qui culpa nobis ratione minus asperiores eum delectus, quas repellendus cum autem veniam iure at! Dicta, ab. Eligendi, qui!",
    category: "category 3",
  },
  {
    id: 4,
    title: "Blog 4",
    image:
      "https://images01.nicepage.com/c461c07a441a5d220e8feb1a/a17abde8d83650a582a28432/users-with-speech-bubbles-vector_53876-82250.jpg",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla quo iusto perferendis aperiam error tenetur vel aliquid voluptate cupiditate nesciunt ipsa, quia laboriosam perspiciatis atque corporis, illo, dolorum fugit asperiores alias dignissimos illum voluptates quasi nobis. Sit ipsam libero, quod vitae amet similique possimus fugit corporis molestias vero, repellendus laudantium sed fugiat dolorum iusto rem beatae! Ut libero sit quaerat eius, laborum dicta pariatur animi ipsa odio officiis et! Culpa odio excepturi accusamus corporis nihil, labore dolorum illo cupiditate rerum odit natus voluptatibus adipisci ipsa modi cumque amet repellat placeat corrupti ullam molestiae distinctio! Ab odio quibusdam quos iure, explicabo facilis recusandae eveniet ea, quod adipisci similique minus tempora nihil, natus nobis est excepturi quaerat doloremque cumque hic dolorum? Sint odit repellat labore accusamus corrupti vero et, necessitatibus optio quas, maiores nesciunt odio veniam. Repellat, ducimus! Possimus, soluta illo, modi repellendus, reprehenderit dolores totam error architecto ut asperiores cum rem sunt blanditiis a quas vitae quo atque libero aliquam consequuntur inventore vero ullam ipsum velit! Molestiae, explicabo. Odio doloribus corporis, in totam ex architecto. Ab tenetur nisi sapiente officia aspernatur blanditiis. Ab, rerum quos ex modi corrupti blanditiis quo dicta numquam quia ipsam suscipit praesentium sit provident animi aspernatur ratione magni nesciunt maxime atque culpa nemo voluptas amet repudiandae. Aperiam, doloremque nesciunt omnis alias, asperiores, architecto aut iure modi aspernatur sed saepe dolor velit atque dicta deserunt impedit error dolore! Quod repudiandae aut consequuntur facere explicabo labore corporis reprehenderit ipsa! Dolores impedit similique exercitationem, esse nobis, cumque voluptatum illum quasi ea nostrum sit voluptatibus totam amet provident accusantium et tenetur quod dignissimos architecto. Atque assumenda, eligendi fugiat hic suscipit amet natus. Aut repudiandae animi dignissimos ea aliquid sed rerum enim doloribus qui culpa nobis ratione minus asperiores eum delectus, quas repellendus cum autem veniam iure at! Dicta, ab. Eligendi, qui!",
    category: "category 4",
  },
  {
    id: 5,
    title: "Blog 5",
    image:
      "https://images01.nicepage.com/c461c07a441a5d220e8feb1a/3b242447f922540fbe750cab/fdf.jpg",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla quo iusto perferendis aperiam error tenetur vel aliquid voluptate cupiditate nesciunt ipsa, quia laboriosam perspiciatis atque corporis, illo, dolorum fugit asperiores alias dignissimos illum voluptates quasi nobis. Sit ipsam libero, quod vitae amet similique possimus fugit corporis molestias vero, repellendus laudantium sed fugiat dolorum iusto rem beatae! Ut libero sit quaerat eius, laborum dicta pariatur animi ipsa odio officiis et! Culpa odio excepturi accusamus corporis nihil, labore dolorum illo cupiditate rerum odit natus voluptatibus adipisci ipsa modi cumque amet repellat placeat corrupti ullam molestiae distinctio! Ab odio quibusdam quos iure, explicabo facilis recusandae eveniet ea, quod adipisci similique minus tempora nihil, natus nobis est excepturi quaerat doloremque cumque hic dolorum? Sint odit repellat labore accusamus corrupti vero et, necessitatibus optio quas, maiores nesciunt odio veniam. Repellat, ducimus! Possimus, soluta illo, modi repellendus, reprehenderit dolores totam error architecto ut asperiores cum rem sunt blanditiis a quas vitae quo atque libero aliquam consequuntur inventore vero ullam ipsum velit! Molestiae, explicabo. Odio doloribus corporis, in totam ex architecto. Ab tenetur nisi sapiente officia aspernatur blanditiis. Ab, rerum quos ex modi corrupti blanditiis quo dicta numquam quia ipsam suscipit praesentium sit provident animi aspernatur ratione magni nesciunt maxime atque culpa nemo voluptas amet repudiandae. Aperiam, doloremque nesciunt omnis alias, asperiores, architecto aut iure modi aspernatur sed saepe dolor velit atque dicta deserunt impedit error dolore! Quod repudiandae aut consequuntur facere explicabo labore corporis reprehenderit ipsa! Dolores impedit similique exercitationem, esse nobis, cumque voluptatum illum quasi ea nostrum sit voluptatibus totam amet provident accusantium et tenetur quod dignissimos architecto. Atque assumenda, eligendi fugiat hic suscipit amet natus. Aut repudiandae animi dignissimos ea aliquid sed rerum enim doloribus qui culpa nobis ratione minus asperiores eum delectus, quas repellendus cum autem veniam iure at! Dicta, ab. Eligendi, qui!",
    category: "category 5",
  },
  {
    id: 6,
    title: "Blog 6",
    image:
      "https://images01.nicepage.com/c461c07a441a5d220e8feb1a/8cc47b39e719570b996d9879/dsds.jpg",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla quo iusto perferendis aperiam error tenetur vel aliquid voluptate cupiditate nesciunt ipsa, quia laboriosam perspiciatis atque corporis, illo, dolorum fugit asperiores alias dignissimos illum voluptates quasi nobis. Sit ipsam libero, quod vitae amet similique possimus fugit corporis molestias vero, repellendus laudantium sed fugiat dolorum iusto rem beatae! Ut libero sit quaerat eius, laborum dicta pariatur animi ipsa odio officiis et! Culpa odio excepturi accusamus corporis nihil, labore dolorum illo cupiditate rerum odit natus voluptatibus adipisci ipsa modi cumque amet repellat placeat corrupti ullam molestiae distinctio! Ab odio quibusdam quos iure, explicabo facilis recusandae eveniet ea, quod adipisci similique minus tempora nihil, natus nobis est excepturi quaerat doloremque cumque hic dolorum? Sint odit repellat labore accusamus corrupti vero et, necessitatibus optio quas, maiores nesciunt odio veniam. Repellat, ducimus! Possimus, soluta illo, modi repellendus, reprehenderit dolores totam error architecto ut asperiores cum rem sunt blanditiis a quas vitae quo atque libero aliquam consequuntur inventore vero ullam ipsum velit! Molestiae, explicabo. Odio doloribus corporis, in totam ex architecto. Ab tenetur nisi sapiente officia aspernatur blanditiis. Ab, rerum quos ex modi corrupti blanditiis quo dicta numquam quia ipsam suscipit praesentium sit provident animi aspernatur ratione magni nesciunt maxime atque culpa nemo voluptas amet repudiandae. Aperiam, doloremque nesciunt omnis alias, asperiores, architecto aut iure modi aspernatur sed saepe dolor velit atque dicta deserunt impedit error dolore! Quod repudiandae aut consequuntur facere explicabo labore corporis reprehenderit ipsa! Dolores impedit similique exercitationem, esse nobis, cumque voluptatum illum quasi ea nostrum sit voluptatibus totam amet provident accusantium et tenetur quod dignissimos architecto. Atque assumenda, eligendi fugiat hic suscipit amet natus. Aut repudiandae animi dignissimos ea aliquid sed rerum enim doloribus qui culpa nobis ratione minus asperiores eum delectus, quas repellendus cum autem veniam iure at! Dicta, ab. Eligendi, qui!",
    category: "category 6",
  },
];
